server:
  port: 80

hosts:
  user-eureka: http://localhost:8089

spring:
  application:
      name: getway-service
  output:
    ansi:
      enabled: always #多彩log

logging:
  level:
    com.rogge: debug
  file: ./logs/getway.log
  root: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${hosts.user-eureka}/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}

zuul:
  routes:
    user:
      path: /user-api/**
      serviceId: user-module
    order:
      path: /order-api/**
      serviceId: order-module
