person:
  name: wulei

hosts:
  user-eureka: http://localhost:8089

server:
  port: 8083

spring:
  application:
      name: order-module
  output:
    ansi:
      enabled: always #多彩log

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

management:
  security:
    enabled: false

logging:
  level:
    com.rogge: debug
  file: ./logs/order.log
  root: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${hosts.user-eureka}/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}
