server:
  port: 80

hosts:
  user-eureka: http://localhost:8089

spring:
  output:
    ansi:
      enabled: always #多彩log
 
management:
  security:
    enabled: false

logging:
  level:
    com.rogge: debug
  file: ./logs/getway.log
  root: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${hosts.user-eureka}/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}

#zuul动态更新路由 在增加时立刻有效  下线时不生效 可能需要一定时间才生效
zuul:
  routes:
    user:
      path: /user-api/**
      serviceId: user-module
    order:
      path: /order-api/**
      serviceId: order-module
#    command:
#      path: /command-api/**
#      serviceId: command-module

