person:
  name: wulei111

hosts:
  user-eureka: http://localhost:8089

server:
  port: 8083

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rogge?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  application:
      name: order-module
#  rabbitmq:
#      host: localhost
#      port: 8161
#      username: admin
#      password: admin
  output:
    ansi:
      enabled: always #多彩log

#不加会无法refresh 禁用验证
management:
  security:
    enabled: false

logging:
  level:
    com.rogge: debug
  file: ./logs/order.log
  root: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${hosts.user-eureka}/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}
